# https://docs.netlify.com/configure-builds/file-based-configuration/
[build]
  command = "npm ci --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "20"
