import type {
  CustomsFile,
  FileStatSummary,
  FileStatusCounts,
  ArchiveStats,
} from '../types';
import { delay } from './utils';

const MOCK: CustomsFile[] = [
  // ── Active files ──────────────────────────────────────────────────────────
  {
    ref: 'IHR-2026-0413',
    customer: 'Tofaş Türk',
    customerCity: 'Bursa',
    status: 'yeni-talep',
    operationType: 'ihracat',
    isArchived: false,
    transportMode: null,
    line: null,
    declarationNo: null,
    receivedAt: '2026-05-25T10:00:00Z',
    lastActivity: 'WhatsApp talebi sisteme aktarıldı',
    assignee: null,
    escalation: false,
    missingDocuments: [],
    systemMailHistory: [
      { type: 'Eksik Evrak Hatırlatma', sentCount: 0, status: 'not_sent' },
      { type: 'GTİP Uyumsuzluk Bildirimi', sentCount: 0, status: 'not_sent' },
      { type: 'Tescil Bilgilendirmesi', sentCount: 0, status: 'not_sent' },
    ],
    createdAt: '2026-05-25T10:00:00Z',
    updatedAt: '2026-05-25T10:00:00Z',
  },
  {
    ref: 'IHR-2026-0410',
    customer: 'BSH Ev Aletleri',
    customerCity: 'Çerkezköy',
    status: 'gtip-hazirlik',
    operationType: 'ihracat',
    isArchived: false,
    transportMode: 'havayolu',
    line: null,
    declarationNo: null,
    receivedAt: '2026-05-23T09:00:00Z',
    lastActivity: 'Fatura parse edildi, GTİP kontrolü',
    assignee: { name: 'M. Demir' },
    escalation: false,
    missingDocuments: ['A.TR Dolaşım Belgesi'],
    systemMailHistory: [
      { type: 'Eksik Evrak Hatırlatma', sentCount: 1, lastSentAt: '2026-05-24T09:00:00Z', status: 'sent' },
      { type: 'GTİP Uyumsuzluk Bildirimi', sentCount: 0, status: 'not_sent' },
      { type: 'Tescil Bilgilendirmesi', sentCount: 0, status: 'not_sent' },
    ],
    createdAt: '2026-05-23T09:00:00Z',
    updatedAt: '2026-05-24T14:00:00Z',
  },
  {
    ref: 'IHR-2026-0409',
    customer: 'Aygaz',
    customerCity: 'Kocaeli',
    status: 'gtip-hazirlik',
    operationType: 'ihracat',
    isArchived: false,
    transportMode: 'karayolu',
    line: null,
    declarationNo: null,
    receivedAt: '2026-05-22T11:30:00Z',
    lastActivity: 'GTİP–malzeme uyumsuzluğu bildirildi',
    assignee: { name: 'S. Kaya' },
    escalation: false,
    missingDocuments: ['Menşe Şahadetnamesi', 'Çeki Listesi'],
    systemMailHistory: [
      { type: 'Eksik Evrak Hatırlatma', sentCount: 2, lastSentAt: '2026-05-24T08:00:00Z', status: 'sent' },
      { type: 'GTİP Uyumsuzluk Bildirimi', sentCount: 1, lastSentAt: '2026-05-23T14:20:00Z', status: 'sent' },
      { type: 'Tescil Bilgilendirmesi', sentCount: 0, status: 'not_sent' },
    ],
    createdAt: '2026-05-22T11:30:00Z',
    updatedAt: '2026-05-24T08:00:00Z',
  },
  {
    ref: 'IHR-2026-0408',
    customer: 'Vestel Ticaret',
    customerCity: 'Manisa',
    status: 'evrak-bekleniyor',
    operationType: 'ihracat',
    isArchived: false,
    transportMode: 'denizyolu',
    line: null,
    declarationNo: null,
    receivedAt: '2026-05-12T10:00:00Z',
    lastActivity: '3. hatırlatma',
    assignee: { name: 'S. Kaya' },
    escalation: true,
    missingDocuments: ['Fatura', 'Çeki Listesi', 'CMR'],
    systemMailHistory: [
      { type: 'Eksik Evrak Hatırlatma', sentCount: 3, lastSentAt: '2026-05-30T10:15:00Z', status: 'sent' },
      { type: 'GTİP Uyumsuzluk Bildirimi', sentCount: 1, lastSentAt: '2026-05-29T16:40:00Z', status: 'sent' },
      { type: 'Tescil Bilgilendirmesi', sentCount: 0, status: 'not_sent' },
    ],
    createdAt: '2026-05-12T10:00:00Z',
    updatedAt: '2026-05-24T17:00:00Z',
  },
  {
    ref: 'IHR-2026-0405',
    customer: 'Şişecam',
    customerCity: 'Mersin',
    status: 'beyanname-yazim',
    operationType: 'ihracat',
    isArchived: false,
    transportMode: 'karayolu',
    line: null,
    declarationNo: '26341700EX004510',
    receivedAt: '2026-05-05T08:00:00Z',
    lastActivity: 'Beyanname alanları dolduruluyor',
    assignee: { name: 'A. Yılmaz' },
    escalation: true,
    missingDocuments: ['Konşimento'],
    systemMailHistory: [
      { type: 'Eksik Evrak Hatırlatma', sentCount: 2, lastSentAt: '2026-05-20T11:00:00Z', status: 'sent' },
      { type: 'GTİP Uyumsuzluk Bildirimi', sentCount: 0, status: 'not_sent' },
      { type: 'Tescil Bilgilendirmesi', sentCount: 0, status: 'not_sent' },
    ],
    createdAt: '2026-05-05T08:00:00Z',
    updatedAt: '2026-05-25T06:00:00Z',
  },
  {
    ref: 'IHR-2026-0411',
    customer: 'Ford Otosan',
    customerCity: 'Kocaeli',
    status: 'ic-kontrol',
    operationType: 'ihracat',
    isArchived: false,
    transportMode: 'karayolu',
    line: null,
    declarationNo: '26341700EX004519',
    receivedAt: '2026-05-21T09:00:00Z',
    lastActivity: 'CMR kap/kilo uyumsuzluğu tespit edildi',
    assignee: { name: 'A. Yılmaz' },
    escalation: true,
    missingDocuments: ['CMR'],
    systemMailHistory: [
      { type: 'Eksik Evrak Hatırlatma', sentCount: 1, lastSentAt: '2026-05-22T09:30:00Z', status: 'sent' },
      { type: 'GTİP Uyumsuzluk Bildirimi', sentCount: 1, lastSentAt: '2026-05-23T08:00:00Z', status: 'failed' },
      { type: 'Tescil Bilgilendirmesi', sentCount: 0, status: 'not_sent' },
    ],
    createdAt: '2026-05-21T09:00:00Z',
    updatedAt: '2026-05-25T09:30:00Z',
  },
  {
    ref: 'IHR-2026-0412',
    customer: 'Arçelik A.Ş.',
    customerCity: 'İstanbul',
    status: 'tescil',
    operationType: 'ihracat',
    isArchived: false,
    transportMode: 'denizyolu',
    line: 'sari',
    declarationNo: '26341700EX004521',
    receivedAt: '2026-05-22T08:00:00Z',
    lastActivity: 'Evrim 1. bildirim alındı, 2. bekleniyor',
    assignee: { name: 'M. Demir' },
    escalation: false,
    missingDocuments: [],
    systemMailHistory: [
      { type: 'Eksik Evrak Hatırlatma', sentCount: 1, lastSentAt: '2026-05-23T10:00:00Z', status: 'sent' },
      { type: 'GTİP Uyumsuzluk Bildirimi', sentCount: 0, status: 'not_sent' },
      { type: 'Tescil Bilgilendirmesi', sentCount: 1, lastSentAt: '2026-05-25T08:45:00Z', status: 'sent' },
    ],
    createdAt: '2026-05-22T08:00:00Z',
    updatedAt: '2026-05-25T10:00:00Z',
  },
  {
    ref: 'IHR-2026-0402',
    customer: 'Eczacıbaşı',
    customerCity: 'İstanbul',
    status: 'tescil',
    operationType: 'ihracat',
    isArchived: false,
    transportMode: 'denizyolu',
    line: 'kirmizi',
    declarationNo: '26341700EX004498',
    receivedAt: '2026-05-08T07:00:00Z',
    lastActivity: 'Kırmızı hat — fiziki muayene bekliyor',
    assignee: { name: 'S. Kaya' },
    escalation: false,
    missingDocuments: [],
    systemMailHistory: [
      { type: 'Eksik Evrak Hatırlatma', sentCount: 0, status: 'not_sent' },
      { type: 'GTİP Uyumsuzluk Bildirimi', sentCount: 0, status: 'not_sent' },
      { type: 'Tescil Bilgilendirmesi', sentCount: 1, lastSentAt: '2026-05-22T14:00:00Z', status: 'sent' },
    ],
    createdAt: '2026-05-08T07:00:00Z',
    updatedAt: '2026-05-24T14:00:00Z',
  },
  {
    ref: 'IHR-2026-0399',
    customer: 'Kordsa',
    customerCity: 'İzmit',
    status: 'kapanis-bekleyen',
    operationType: 'ihracat',
    isArchived: false,
    transportMode: 'karayolu',
    line: 'yesil',
    declarationNo: '26341700EX004471',
    receivedAt: '2026-05-01T11:00:00Z',
    lastActivity: 'Teslim-tesellüm yüklendi, para talep açık',
    assignee: { name: 'M. Demir' },
    escalation: false,
    missingDocuments: [],
    systemMailHistory: [
      { type: 'Eksik Evrak Hatırlatma', sentCount: 1, lastSentAt: '2026-05-10T09:00:00Z', status: 'sent' },
      { type: 'GTİP Uyumsuzluk Bildirimi', sentCount: 0, status: 'not_sent' },
      { type: 'Tescil Bilgilendirmesi', sentCount: 1, lastSentAt: '2026-05-18T11:30:00Z', status: 'sent' },
    ],
    createdAt: '2026-05-01T11:00:00Z',
    updatedAt: '2026-05-23T16:00:00Z',
  },

  // ── Archived files ────────────────────────────────────────────────────────

  // İhracat arşivi
  {
    ref: 'IHR-2026-0395',
    customer: 'Brisa',
    customerCity: 'İzmit',
    status: 'kapandi',
    operationType: 'ihracat',
    isArchived: true,
    transportMode: 'havayolu',
    line: 'mavi',
    declarationNo: '26341700EX004460',
    receivedAt: '2026-04-28T09:00:00Z',
    closedAt: '2026-05-22T11:00:00Z',
    lastActivity: 'Kapanış paketi müşteriye iletildi',
    assignee: { name: 'A. Yılmaz' },
    escalation: false,
    missingDocuments: [],
    systemMailHistory: [
      { type: 'Eksik Evrak Hatırlatma', sentCount: 2, lastSentAt: '2026-05-05T10:00:00Z', status: 'sent' },
      { type: 'GTİP Uyumsuzluk Bildirimi', sentCount: 0, status: 'not_sent' },
      { type: 'Tescil Bilgilendirmesi', sentCount: 1, lastSentAt: '2026-05-15T09:20:00Z', status: 'sent' },
    ],
    createdAt: '2026-04-28T09:00:00Z',
    updatedAt: '2026-05-22T11:00:00Z',
  },
  {
    ref: 'IHR-2026-0389',
    customer: 'Valeo eAutomotive',
    customerCity: 'Veszprem',
    status: 'kapandi',
    operationType: 'ihracat',
    isArchived: true,
    transportMode: 'karayolu',
    line: 'yesil',
    declarationNo: '26341700EX004441',
    receivedAt: '2026-04-18T08:30:00Z',
    closedAt: '2026-05-10T14:00:00Z',
    lastActivity: 'Kapanış tamamlandı',
    assignee: { name: 'M. Demir' },
    escalation: true,
    missingDocuments: [],
    systemMailHistory: [
      { type: 'Tescil Bilgilendirmesi', sentCount: 1, lastSentAt: '2026-05-02T10:00:00Z', status: 'sent' },
    ],
    createdAt: '2026-04-18T08:30:00Z',
    updatedAt: '2026-05-10T14:00:00Z',
  },

  // İthalat arşivi
  {
    ref: 'ITH-2026-0281',
    customer: 'Anadolu Tekstil A.Ş.',
    customerCity: 'İstanbul',
    status: 'kapandi',
    operationType: 'ithalat',
    isArchived: true,
    transportMode: 'denizyolu',
    line: 'yesil',
    declarationNo: '26341700IM004382',
    receivedAt: '2026-04-20T10:00:00Z',
    closedAt: '2026-05-02T16:00:00Z',
    lastActivity: 'Kapanış paketi gönderildi',
    assignee: { name: 'S. Kaya' },
    escalation: false,
    missingDocuments: [],
    systemMailHistory: [
      { type: 'Tescil Bilgilendirmesi', sentCount: 1, lastSentAt: '2026-04-29T09:00:00Z', status: 'sent' },
    ],
    createdAt: '2026-04-20T10:00:00Z',
    updatedAt: '2026-05-02T16:00:00Z',
  },
  {
    ref: 'ITH-2026-0271',
    customer: 'Marmara Makine Ltd.',
    customerCity: 'İstanbul',
    status: 'kapandi',
    operationType: 'ithalat',
    isArchived: true,
    transportMode: 'karayolu',
    line: 'mavi',
    declarationNo: '26341700IM004351',
    receivedAt: '2026-04-05T09:00:00Z',
    closedAt: '2026-04-15T11:30:00Z',
    lastActivity: 'Kapanış onaylandı',
    assignee: { name: 'A. Yılmaz' },
    escalation: false,
    missingDocuments: [],
    systemMailHistory: [
      { type: 'Tescil Bilgilendirmesi', sentCount: 1, lastSentAt: '2026-04-10T10:00:00Z', status: 'sent' },
    ],
    createdAt: '2026-04-05T09:00:00Z',
    updatedAt: '2026-04-15T11:30:00Z',
  },
  {
    ref: 'ITH-2026-0268',
    customer: 'Ege Kimya A.Ş.',
    customerCity: 'İzmir',
    status: 'kapandi',
    operationType: 'ithalat',
    isArchived: true,
    transportMode: 'denizyolu',
    line: 'kirmizi',
    declarationNo: '26341700IM004339',
    receivedAt: '2026-03-28T08:00:00Z',
    closedAt: '2026-04-08T15:00:00Z',
    lastActivity: 'Kapanış tamamlandı — fiziki kontrol geçti',
    assignee: { name: 'M. Demir' },
    escalation: true,
    missingDocuments: [],
    systemMailHistory: [
      { type: 'GTİP Uyumsuzluk Bildirimi', sentCount: 1, lastSentAt: '2026-04-01T08:00:00Z', status: 'sent' },
      { type: 'Tescil Bilgilendirmesi', sentCount: 1, lastSentAt: '2026-04-04T09:00:00Z', status: 'sent' },
    ],
    createdAt: '2026-03-28T08:00:00Z',
    updatedAt: '2026-04-08T15:00:00Z',
  },

  // Transit arşivi
  {
    ref: 'TRN-2026-0155',
    customer: 'Ford Otosan',
    customerCity: 'Kocaeli',
    status: 'kapandi',
    operationType: 'transit',
    isArchived: true,
    transportMode: 'karayolu',
    line: 'yesil',
    declarationNo: '26341700TR004208',
    receivedAt: '2026-03-20T09:00:00Z',
    closedAt: '2026-03-28T13:00:00Z',
    lastActivity: 'Transit kapandı',
    assignee: { name: 'S. Kaya' },
    escalation: false,
    missingDocuments: [],
    systemMailHistory: [
      { type: 'Tescil Bilgilendirmesi', sentCount: 1, lastSentAt: '2026-03-25T10:00:00Z', status: 'sent' },
    ],
    createdAt: '2026-03-20T09:00:00Z',
    updatedAt: '2026-03-28T13:00:00Z',
  },
  {
    ref: 'TRN-2026-0148',
    customer: 'Arçelik A.Ş.',
    customerCity: 'İstanbul',
    status: 'kapandi',
    operationType: 'transit',
    isArchived: true,
    transportMode: 'havayolu',
    line: 'mavi',
    declarationNo: '26341700TR004190',
    receivedAt: '2026-03-08T10:00:00Z',
    closedAt: '2026-03-14T16:00:00Z',
    lastActivity: 'Transit kapandı — eksiksizksin',
    assignee: { name: 'A. Yılmaz' },
    escalation: false,
    missingDocuments: [],
    systemMailHistory: [
      { type: 'Tescil Bilgilendirmesi', sentCount: 1, lastSentAt: '2026-03-12T09:00:00Z', status: 'sent' },
    ],
    createdAt: '2026-03-08T10:00:00Z',
    updatedAt: '2026-03-14T16:00:00Z',
  },
];

export const STAT_SUMMARY: FileStatSummary = {
  aktifDosya: 47,
  evrakBekleyen: 12,
  beyannamedYazim: 4,
  eskalasyon: 3,
  tescilde: 8,
};

export const STATUS_COUNTS: FileStatusCounts = {
  total: 47,
  yeniTalep: 6,
  gtipHazirlik: 7,
  evrakBekleniyor: 12,
  beyanname: 4,
  icKontrol: 5,
  tescil: 8,
  kapanisBekleyen: 9,
};

export const filesService = {
  /** Active (non-archived) files only. */
  list: async (): Promise<CustomsFile[]> => {
    const live = await import('./liveApi').then((m) => m.fetchCustomsFiles());
    if (live?.length) return live.filter((f) => !f.isArchived);
    await delay(120);
    return MOCK.filter((f) => !f.isArchived).map((f) => ({ ...f }));
  },
  get: async (ref: string): Promise<CustomsFile | null> => {
    await delay(80);
    return MOCK.find((f) => f.ref === ref) ?? null;
  },
  /** Archived files, optionally filtered by operationType. */
  listArchived: async (operationType?: string): Promise<CustomsFile[]> => {
    await delay(100);
    return MOCK.filter(
      (f) => f.isArchived && (!operationType || f.operationType === operationType)
    ).map((f) => ({ ...f }));
  },
  /** Stats for the archive screen (per operation type). */
  getArchivedStats: async (operationType: string): Promise<ArchiveStats> => {
    await delay(60);
    const now = new Date();
    const records = MOCK.filter((f) => f.isArchived && f.operationType === operationType);
    const thisMonth = records.filter((f) => {
      if (!f.closedAt) return false;
      const d = new Date(f.closedAt);
      return d.getFullYear() === now.getFullYear() && d.getMonth() === now.getMonth();
    });
    const clean  = records.filter((f) => !f.escalation && f.missingDocuments.length === 0);
    const warned = records.filter((f) =>  f.escalation || f.missingDocuments.length > 0);
    return { total: records.length, thisMonth: thisMonth.length, clean: clean.length, warned: warned.length };
  },
};
