import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import mongoose from "mongoose";
import { env } from "../../src/config/env.js";
import { DocumentType } from "../../src/common/enums/documentType.js";
import { DeclarationModel } from "../../src/modules/declarations/declaration.model.js";
import { UploadedFileModel } from "../../src/modules/documents/document.model.js";
import { LogicalDocumentModel } from "../../src/modules/idp/domain/logicalDocument.model.js";
import { ProcessingRunModel } from "../../src/modules/idp/domain/processingRun.model.js";
import { DeclarationFieldResolutionRunModel } from "../../src/modules/idp/domain/declarationFieldResolution.model.js";
import { ProcessingStatus } from "../../src/modules/idp/domain/idp.types.js";
import { normalizeModelExtractionArtifacts } from "../../src/modules/idp/domain/modelExtractionArtifactPersistence.js";
import { normalizeInvoiceVisionCheckpoint } from "../../src/modules/idp/llm/invoiceVisionCheckpoint.js";
import { enqueueDocumentProcessing } from "../../src/modules/idp/queue/idpProcessing.service.js";
import { closeIdpQueue, getIdpQueue } from "../../src/modules/idp/queue/idpQueue.js";
import { PRODUCT_E2E_GENERALIZATION_CASES as CASES, PRODUCT_E2E_GENERALIZATION_CORPUS_ROOT as ROOT } from "./productE2EGeneralizationGroundTruth.js";

const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const norm=(v:unknown)=>String(v??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/İ/g,"I").toUpperCase().replace(/\s+/g," ").trim();
const compact=(v:unknown)=>norm(v).replace(/[^A-Z0-9.]/g,"");
function containsValue(obj:unknown, expected:unknown):boolean { const target=compact(expected); if(!target)return false; const walk=(v:any):boolean=>{if(v==null)return false;if(typeof v==="string"||typeof v==="number"){const c=compact(v);return c===target||(target.length>=5&&c.includes(target))||(c.length>=5&&target.includes(c));}if(Array.isArray(v))return v.some(walk);if(typeof v==="object")return Object.values(v).some(walk);return false;};return walk(obj); }
function flattenExpected(tc:any){const out:{field:string,value:unknown}[]=[];for(const [k,v] of Object.entries(tc.expected??{})){if(k!=="goodsLines"&&v!==undefined)out.push({field:k,value:v});}for(let i=0;i<(tc.expected?.goodsLines??[]).length;i++)for(const [k,v] of Object.entries(tc.expected.goodsLines[i]))if(v!==undefined)out.push({field:`goodsLines[${i}].${k}`,value:v});return out;}
function readFinal(nd:any,field:string){if(field==="invoiceNumber")return nd?.header?.invoiceNo;if(field==="currency")return nd?.header?.currency;if(field==="deliveryTerm")return nd?.trade?.deliveryTerm;if(field==="invoiceDate")return nd?.header?.invoiceDate;if(field==="grossWeight")return nd?.packageInfo?.grossKg;if(field==="netWeight")return nd?.packageInfo?.netKg;if(field==="originCountry")return nd?.trade?.origin;const m=/^goodsLines\[(\d+)\]\.(.+)$/.exec(field);return m?nd?.goodsLines?.[Number(m[1])]?.[m[2]]:undefined;}
function countCandidates(snapshot:any){if(!snapshot||typeof snapshot!=="object")return 0;const fields=(snapshot as any).fields;if(fields&&typeof fields==="object")return Object.values(fields).reduce((n:number,v:any)=>n+(Array.isArray(v)?v.length:0),0);if(Array.isArray((snapshot as any).segments))return (snapshot as any).segments.reduce((n:number,s:any)=>n+countCandidates(s?.data?.fieldCandidates),0);return 0;}
async function waitTerminal(runId:string,id:string,timeout=120*60_000){const end=Date.now()+timeout;let last="";while(Date.now()<end){const run:any=await ProcessingRunModel.findById(runId).lean();assert(run,`${id}: run disappeared`);const job=await getIdpQueue().getJob(runId);assert(job,`${id}: job disappeared`);const state=await job.getState();const snap=`${run.status}/${run.currentStage}/${state}/attempt=${run.attempt}`;if(snap!==last){console.log(JSON.stringify({event:"product-e2e-1.6.8.11.case.progress",id,state:snap}));last=snap;}if(run.status===ProcessingStatus.FAILED||state==="failed")throw new Error(`${id}: worker failed: ${JSON.stringify(run.error)}`);if((run.status===ProcessingStatus.COMPLETED||run.status===ProcessingStatus.REVIEW_REQUIRED)&&state==="completed")return run;await sleep(500);}throw new Error(`${id}: timeout`);}

function numberOf(v:unknown){return typeof v==="number"?v:Number(String(v??"").replace(/\s/g,"").replace(/,/g,"."));}
function eqNum(a:unknown,e:unknown){const av=numberOf(a),ev=numberOf(e);return Number.isFinite(av)&&Number.isFinite(ev)&&Math.abs(av-ev)<=Math.max(1e-6,Math.abs(ev)*1e-6);}
function canonUnit(v:unknown){const n=norm(v);const aliases:Record<string,string>={ADET:"EA",EA:"EA",PCS:"EA",PIECE:"EA",KUTU:"BOX",BOX:"BOX",PAKET:"PACK",PACK:"PACK"};return aliases[n]??n;}
function canonCurrency(v:unknown){const n=norm(v).replace(/[^A-Z]/g,"");const aliases:Record<string,string>={TL:"TRY",TRY:"TRY",TURKLIRASI:"TRY",USD:"USD",US$:"USD",EUR:"EUR"};return aliases[n]??n;}
function canonCountry(v:unknown){const n=norm(v).replace(/[^A-Z]/g,"");const aliases:Record<string,string>={US:"US",USA:"US",ABD:"US",UNITEDSTATES:"US",UNITEDSTATESOFAMERICA:"US",TR:"TR",TURKIYE:"TR",TURKEY:"TR",DE:"DE",GERMANY:"DE",ALMANYA:"DE"};return aliases[n]??n;}
function canonDate(v:unknown){const s=String(v??"").trim();const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(s);return m?`${m[1]}-${m[2]}-${m[3]}`:s;}
function semanticCompare(field:string,actual:unknown,expected:unknown){if(actual===undefined||actual===null)return{status:"MISSING",equivalent:false};if(typeof expected==="number")return{status:eqNum(actual,expected)?"EXACT":"WRONG",equivalent:eqNum(actual,expected)};const rawExact=String(actual)===String(expected);if(rawExact)return{status:"EXACT",equivalent:true};let equivalent=false;if(field.endsWith(".unit"))equivalent=canonUnit(actual)===canonUnit(expected);else if(field==="currency")equivalent=canonCurrency(actual)===canonCurrency(expected);else if(field==="originCountry")equivalent=canonCountry(actual)===canonCountry(expected);else if(field==="invoiceDate")equivalent=canonDate(actual)===canonDate(expected);else if(field.endsWith(".descriptionContains"))equivalent=norm(actual).includes(norm(expected));else equivalent=norm(actual)===norm(expected);return{status:equivalent?"SEMANTIC_EQUIVALENT":"WRONG",equivalent};}
function semanticRows(artifacts:any[]){const rows:any[]=[];for(const artifact of [...artifacts].sort((a,b)=>(a.pageNumbers?.[0]??0)-(b.pageNumbers?.[0]??0))){const goods:Record<string,unknown[]>={};for(const f of artifact.parsedSemanticResponse.fields??[]){if(f.field.startsWith("goodsLines[].")&&Array.isArray(f.value))goods[f.field.slice(13)]=f.value;}const n=Math.max(0,...Object.values(goods).map(v=>v.length));for(let i=0;i<n;i++)rows.push(Object.fromEntries(Object.entries(goods).map(([k,v])=>[k,v[i]])));}return rows;}
function matchRows(expected:any[],actual:any[]){const used=new Set<number>();return expected.map((e,expectedIndex)=>{let best=-1,bestScore=-1;for(let i=0;i<actual.length;i++){if(used.has(i))continue;const a=actual[i]??{};let score=0;if(e.descriptionContains!==undefined&&norm(a.description).includes(norm(e.descriptionContains)))score+=4;if(e.hsCode!==undefined&&String(a.hsCode??"").replace(/\D/g,"")===String(e.hsCode).replace(/\D/g,""))score+=3;if(e.quantity!==undefined&&eqNum(a.quantity,e.quantity))score+=2;if(e.lineTotal!==undefined&&eqNum(a.lineTotal,e.lineTotal))score+=2;if(e.unitPrice!==undefined&&eqNum(a.unitPrice,e.unitPrice))score+=1;if(e.unit!==undefined&&norm(a.unit)===norm(e.unit))score+=1;if(score>bestScore){bestScore=score;best=i;}}if(best>=0)used.add(best);return{expectedIndex,matchedActualIndex:best,matchScore:bestScore,expected:e,actual:best>=0?actual[best]:null};});}

async function main(){
 assert.equal(env.llmEnabled,true,"1.6.8.7 requires LLM_ENABLED=true");assert.equal(env.llmVisionEnabled,true,"1.6.8.7 requires LLM_VISION_ENABLED=true");
 const requested=(process.env.GENERALIZATION_CASES??"mekar-ear-0068").split(",").map(x=>x.trim()).filter(Boolean);const selected=CASES.filter((x:any)=>requested.includes(x.id));assert.equal(selected.length,requested.length,`Unknown GENERALIZATION_CASES=${requested.join(",")}`);
 await mongoose.connect(env.mongoUri);try{for(const tc of selected as any[]){const pdfPath=path.join(ROOT,tc.pdf);const bytes=await fs.readFile(pdfPath);assert.equal(createHash("sha256").update(bytes).digest("hex"),tc.sourceSha256,`${tc.id}: frozen source changed`);const companyId=new mongoose.Types.ObjectId(),declarationId=new mongoose.Types.ObjectId();let uploadedId:any,runId="";try{
  await DeclarationModel.create({_id:declarationId,companyId,status:"DRAFT",normalizedData:{}});const stat=await fs.stat(pdfPath);const up:any=await UploadedFileModel.create({companyId,declarationId,type:DocumentType.INVOICE,fileName:tc.pdf,filePath:pdfPath,mimeType:"application/pdf",size:stat.size,extractionStatus:"PENDING",parseErrors:[]});uploadedId=up._id;const queued:any=await enqueueDocumentProcessing({companyId,declarationId:String(declarationId),uploadedFileId:String(uploadedId)});runId=String(queued._id);const terminal:any=await waitTerminal(runId,tc.id);
  const run:any=await ProcessingRunModel.findById(runId).lean();const declaration:any=await DeclarationModel.findById(declarationId).lean();const audits:any[]=await DeclarationFieldResolutionRunModel.find({companyId,declarationId}).lean();const checkpoint=normalizeInvoiceVisionCheckpoint(run?.visionCandidateCheckpoint);const pageExecution=Object.entries(checkpoint.segments).flatMap(([segmentId,segment])=>Object.values(segment.pages).sort((a,b)=>a.pageNumber-b.pageNumber).map(page=>({segmentId,pageNumber:page.pageNumber,status:page.status,decision:page.decision??null,candidateCount:page.candidateCount??0,hasCandidates:Boolean(page.candidates&&Object.keys(page.candidates.fields??{}).length),hasExtractionArtifact:Boolean(page.extractionArtifact),artifactFieldCount:page.extractionArtifact?.parsedSemanticResponse?.fields?.length??0,artifactDecision:page.extractionArtifact?.parsedSemanticResponse?.decision??null,error:page.error??null})));const artifacts=normalizeModelExtractionArtifacts(run?.modelExtractionArtifacts);
  console.log(JSON.stringify({event:"product-e2e-1.6.8.11.vision-page-execution.diagnosed",id:tc.id,workerOutcome:terminal.status,executionKey:checkpoint.executionKey??null,pageExecution,firstClassArtifactPages:artifacts.flatMap(a=>a.pageNumbers),firstClassArtifactCount:artifacts.length,guardrails:{measurementOnly:true,productionExtractionChanged:false,secondGroundTruthAwareModelCall:false,supplierSpecificRules:false,directNormalizedWrite:false}},null,2));
  const artifactSemantic={pages:artifacts.flatMap(a=>a.pageNumbers),decisions:[...new Set(artifacts.map(a=>a.parsedSemanticResponse.decision))],fieldCount:artifacts.reduce((n,a)=>n+a.parsedSemanticResponse.fields.length,0),fields:artifacts.flatMap(a=>a.parsedSemanticResponse.fields.map(f=>({field:f.field,value:f.value,confidence:f.confidence,evidenceCount:f.evidence.length}))),issues:artifacts.flatMap(a=>a.parsedSemanticResponse.issues)};
  const artifactRows=semanticRows(artifacts);const finalRows=Array.isArray(declaration?.normalizedData?.goodsLines)?declaration.normalizedData.goodsLines:[];const expectedRows=tc.expected?.goodsLines??[];const artifactMatches=matchRows(expectedRows,artifactRows);const finalMatches=matchRows(expectedRows,finalRows);const actualRowMatches=artifactMatches.map((m:any,i:number)=>{const fm=finalMatches[i];const idx=m.matchedActualIndex;const prefix=idx>=0?`goodsLines.${idx}.`:"";const f6Fields=audits.flatMap((a:any)=>Object.keys(a?.resolution?.fields??{})).filter((f:string)=>prefix&&f.startsWith(prefix));return{expectedIndex:i,artifactMatchedIndex:idx,artifactMatchScore:m.matchScore,artifactRow:m.actual,workerCandidateFields:prefix?Object.keys(run?.candidates?.fields??{}).filter((f:string)=>f.startsWith(prefix)):[],declarationCandidateFields:prefix?Object.keys(run?.declarationCandidates?.fields??{}).filter((f:string)=>f.startsWith(prefix)):[],f6ResolutionFields:f6Fields,finalMatchedIndex:fm?.matchedActualIndex??-1,finalMatchScore:fm?.matchScore??-1,finalRow:fm?.actual??null};});
  console.log(JSON.stringify({event:"product-e2e-1.6.8.11.actual-row-matched-stage.diagnosed",id:tc.id,artifactRowCount:artifactRows.length,finalRowCount:finalRows.length,rowMatches:actualRowMatches,guardrails:{measurementOnly:true,groundTruthUsedForMeasurementOnly:true,secondGroundTruthAwareModelCall:false,productionExtractionChanged:false,supplierSpecificRules:false,directNormalizedWrite:false}},null,2));
  const scalarFields=Object.entries(tc.expected??{}).filter(([k,v])=>k!=="goodsLines"&&v!==undefined).map(([field,expected])=>{const actual=readFinal(declaration?.normalizedData??{},field);return{field,expected,actual,...semanticCompare(field,actual,expected)};});
  const goodsFields=actualRowMatches.flatMap((m:any)=>Object.entries(m.expected??{}).map(([leaf,expected])=>{const field=`goodsLines[${m.expectedIndex}].${leaf}`;const actualLeaf=leaf==="descriptionContains"?"description":leaf;const actual=m.finalRow?.[actualLeaf];return{field,expected,actual,matchedFinalIndex:m.finalMatchedIndex,...semanticCompare(field,actual,expected)};}));
  const semanticFields=[...scalarFields,...goodsFields];const semanticCounts=semanticFields.reduce((a:any,x:any)=>(a[x.status]=(a[x.status]??0)+1,a),{});const rawScalarCandidates=artifacts.flatMap(a=>a.parsedSemanticResponse.fields).filter(f=>["currency","invoiceDate","origin"].includes(f.field)).map(f=>({field:f.field,value:f.value,pageNumbers:artifacts.find(a=>a.parsedSemanticResponse.fields.includes(f))?.pageNumbers??[]}));
  console.log(JSON.stringify({event:"product-e2e-1.6.8.11.semantic-accuracy.measured",id:tc.id,counts:semanticCounts,total:semanticFields.length,fields:semanticFields,rawScalarCandidates,notes:{semanticEquivalenceDoesNotEraseRawConflicts:true,rowMatchingUsesPhysicalMatchedRows:true,measurementOnly:true},guardrails:{productionExtractionChanged:false,groundTruthUsedForMeasurementOnly:true,supplierSpecificRules:false,directNormalizedWrite:false}},null,2));
  const expected=flattenExpected(tc);const boundaries=expected.map(({field,value})=>{const inArtifact=containsValue(artifacts,value),inWorkerCandidates=containsValue(run?.candidates,value),inDeclarationCandidates=containsValue(run?.declarationCandidates,value),inWorkerResolution=containsValue(run?.resolvedResult,value),inF6Audit=containsValue(audits,value),finalValue=readFinal(declaration?.normalizedData??{},field),inFinal=containsValue(finalValue,value);let lossBoundary="MODEL_OUTPUT_MISSING";if(inFinal)lossBoundary="FINAL_PRESENT";else if(inF6Audit)lossBoundary="F6_RESOLUTION_OR_PROMOTION_LOSS";else if(inWorkerResolution)lossBoundary="DECLARATION_PROJECTION_OR_F6_LOSS";else if(inDeclarationCandidates)lossBoundary="WORKER_RESOLUTION_LOSS";else if(inWorkerCandidates)lossBoundary="DECLARATION_CANDIDATE_PROJECTION_LOSS";else if(inArtifact)lossBoundary="MODEL_ARTIFACT_TO_WORKER_CANDIDATE_LOSS";return {field,expected:value,inArtifact,inWorkerCandidates,inDeclarationCandidates,inWorkerResolution,inF6Audit,finalValue,inFinal,lossBoundary};});
  const counts=boundaries.reduce((a:any,x:any)=>(a[x.lossBoundary]=(a[x.lossBoundary]??0)+1,a),{});console.log(JSON.stringify({event:"product-e2e-1.6.8.7.row-matched-stage.diagnosed",id:tc.id,mode:tc.mode,workerOutcome:terminal.status,artifactSemantic,stageCounts:{workerCandidates:countCandidates(run?.candidates),declarationCandidates:countCandidates(run?.declarationCandidates),f6ResolutionRuns:audits.length},lossBoundaryCounts:counts,fields:boundaries,diagnosticNote:"goods-line ground truth is a representative subset; raw index boundaries are informational only and must not be interpreted as row-loss proof",guardrails:{measurementOnly:true,rowMatchingRequiredForGoodsLines:true,secondGroundTruthAwareModelCall:false,productionExtractionChanged:false,supplierSpecificRules:false,directNormalizedWrite:false}},null,2));
 }finally{if(runId){const job=await getIdpQueue().getJob(runId);if(job)try{await job.remove();}catch{}}await DeclarationFieldResolutionRunModel.deleteMany({declarationId});await LogicalDocumentModel.deleteMany({declarationId});if(runId)await ProcessingRunModel.deleteMany({_id:runId});if(uploadedId)await UploadedFileModel.deleteMany({_id:uploadedId});await DeclarationModel.deleteMany({_id:declarationId});}}
 }finally{await closeIdpQueue();await mongoose.disconnect();}}
main().catch(async e=>{console.error(e);try{await closeIdpQueue();}catch{}try{await mongoose.disconnect();}catch{}process.exitCode=1;});
