import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import mongoose from "mongoose";
import { env } from "../../src/config/env.js";
import { DocumentType } from "../../src/common/enums/documentType.js";
import { DeclarationModel } from "../../src/modules/declarations/declaration.model.js";
import { UploadedFileModel } from "../../src/modules/documents/document.model.js";
import { LogicalDocumentModel } from "../../src/modules/idp/domain/logicalDocument.model.js";
import { ProcessingRunModel } from "../../src/modules/idp/domain/processingRun.model.js";
import { DeclarationFieldResolutionRunModel } from "../../src/modules/idp/domain/declarationFieldResolution.model.js";
import { ProcessingStatus } from "../../src/modules/idp/domain/idp.types.js";
import { normalizeModelExtractionArtifacts } from "../../src/modules/idp/domain/modelExtractionArtifactPersistence.js";
import { enqueueDocumentProcessing } from "../../src/modules/idp/queue/idpProcessing.service.js";
import { closeIdpQueue, getIdpQueue } from "../../src/modules/idp/queue/idpQueue.js";
import { PRODUCT_E2E_GENERALIZATION_CASES as CASES, PRODUCT_E2E_GENERALIZATION_CORPUS_ROOT as ROOT } from "./productE2EGeneralizationGroundTruth.js";

const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const norm=(v:unknown)=>String(v??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/İ/g,"I").toUpperCase().replace(/\s+/g," ").trim();
const compact=(v:unknown)=>norm(v).replace(/[^A-Z0-9.]/g,"");
function containsValue(obj:unknown, expected:unknown):boolean { const target=compact(expected); if(!target)return false; const walk=(v:any):boolean=>{if(v==null)return false;if(typeof v==="string"||typeof v==="number"){const c=compact(v);return c===target||(target.length>=5&&c.includes(target))||(c.length>=5&&target.includes(c));}if(Array.isArray(v))return v.some(walk);if(typeof v==="object")return Object.values(v).some(walk);return false;};return walk(obj); }
function flattenExpected(tc:any){const out:{field:string,value:unknown}[]=[];for(const [k,v] of Object.entries(tc.expected??{})){if(k!=="goodsLines"&&v!==undefined)out.push({field:k,value:v});}for(let i=0;i<(tc.expected?.goodsLines??[]).length;i++)for(const [k,v] of Object.entries(tc.expected.goodsLines[i]))if(v!==undefined)out.push({field:`goodsLines[${i}].${k}`,value:v});return out;}
function readFinal(nd:any,field:string){if(field==="invoiceNumber")return nd?.header?.invoiceNo;if(field==="currency")return nd?.header?.currency;if(field==="deliveryTerm")return nd?.trade?.deliveryTerm;if(field==="invoiceDate")return nd?.header?.invoiceDate;if(field==="grossWeight")return nd?.packageInfo?.grossKg;if(field==="netWeight")return nd?.packageInfo?.netKg;if(field==="originCountry")return nd?.trade?.origin;const m=/^goodsLines\[(\d+)\]\.(.+)$/.exec(field);return m?nd?.goodsLines?.[Number(m[1])]?.[m[2]]:undefined;}
function countCandidates(snapshot:any){if(!snapshot||typeof snapshot!=="object")return 0;const fields=(snapshot as any).fields;if(fields&&typeof fields==="object")return Object.values(fields).reduce((n:number,v:any)=>n+(Array.isArray(v)?v.length:0),0);if(Array.isArray((snapshot as any).segments))return (snapshot as any).segments.reduce((n:number,s:any)=>n+countCandidates(s?.data?.fieldCandidates),0);return 0;}
async function waitTerminal(runId:string,id:string,timeout=120*60_000){const end=Date.now()+timeout;let last="";while(Date.now()<end){const run:any=await ProcessingRunModel.findById(runId).lean();assert(run,`${id}: run disappeared`);const job=await getIdpQueue().getJob(runId);assert(job,`${id}: job disappeared`);const state=await job.getState();const snap=`${run.status}/${run.currentStage}/${state}/attempt=${run.attempt}`;if(snap!==last){console.log(JSON.stringify({event:"product-e2e-1.6.8.6.case.progress",id,state:snap}));last=snap;}if(run.status===ProcessingStatus.FAILED||state==="failed")throw new Error(`${id}: worker failed: ${JSON.stringify(run.error)}`);if((run.status===ProcessingStatus.COMPLETED||run.status===ProcessingStatus.REVIEW_REQUIRED)&&state==="completed")return run;await sleep(500);}throw new Error(`${id}: timeout`);}
async function main(){
 assert.equal(env.llmEnabled,true,"1.6.8.6 requires LLM_ENABLED=true");assert.equal(env.llmVisionEnabled,true,"1.6.8.6 requires LLM_VISION_ENABLED=true");
 const requested=(process.env.GENERALIZATION_CASES??"mekar-ear-0068").split(",").map(x=>x.trim()).filter(Boolean);const selected=CASES.filter((x:any)=>requested.includes(x.id));assert.equal(selected.length,requested.length,`Unknown GENERALIZATION_CASES=${requested.join(",")}`);
 await mongoose.connect(env.mongoUri);try{for(const tc of selected as any[]){const pdfPath=path.join(ROOT,tc.pdf);const bytes=await fs.readFile(pdfPath);assert.equal(createHash("sha256").update(bytes).digest("hex"),tc.sourceSha256,`${tc.id}: frozen source changed`);const companyId=new mongoose.Types.ObjectId(),declarationId=new mongoose.Types.ObjectId();let uploadedId:any,runId="";try{
  await DeclarationModel.create({_id:declarationId,companyId,status:"DRAFT",normalizedData:{}});const stat=await fs.stat(pdfPath);const up:any=await UploadedFileModel.create({companyId,declarationId,type:DocumentType.INVOICE,fileName:tc.pdf,filePath:pdfPath,mimeType:"application/pdf",size:stat.size,extractionStatus:"PENDING",parseErrors:[]});uploadedId=up._id;const queued:any=await enqueueDocumentProcessing({companyId,declarationId:String(declarationId),uploadedFileId:String(uploadedId)});runId=String(queued._id);const terminal:any=await waitTerminal(runId,tc.id);
  const run:any=await ProcessingRunModel.findById(runId).lean();const declaration:any=await DeclarationModel.findById(declarationId).lean();const audits:any[]=await DeclarationFieldResolutionRunModel.find({companyId,declarationId}).lean();const artifacts=normalizeModelExtractionArtifacts(run?.modelExtractionArtifacts);assert.ok(artifacts.length>0,`${tc.id}: no first-class model artifact`);
  const artifactSemantic={pages:artifacts.flatMap(a=>a.pageNumbers),decisions:[...new Set(artifacts.map(a=>a.parsedSemanticResponse.decision))],fieldCount:artifacts.reduce((n,a)=>n+a.parsedSemanticResponse.fields.length,0),fields:artifacts.flatMap(a=>a.parsedSemanticResponse.fields.map(f=>({field:f.field,value:f.value,confidence:f.confidence,evidenceCount:f.evidence.length}))),issues:artifacts.flatMap(a=>a.parsedSemanticResponse.issues)};
  const expected=flattenExpected(tc);const boundaries=expected.map(({field,value})=>{const inArtifact=containsValue(artifacts,value),inWorkerCandidates=containsValue(run?.candidates,value),inDeclarationCandidates=containsValue(run?.declarationCandidates,value),inWorkerResolution=containsValue(run?.resolvedResult,value),inF6Audit=containsValue(audits,value),finalValue=readFinal(declaration?.normalizedData??{},field),inFinal=containsValue(finalValue,value);let lossBoundary="MODEL_OUTPUT_MISSING";if(inFinal)lossBoundary="FINAL_PRESENT";else if(inF6Audit)lossBoundary="F6_RESOLUTION_OR_PROMOTION_LOSS";else if(inWorkerResolution)lossBoundary="DECLARATION_PROJECTION_OR_F6_LOSS";else if(inDeclarationCandidates)lossBoundary="WORKER_RESOLUTION_LOSS";else if(inWorkerCandidates)lossBoundary="DECLARATION_CANDIDATE_PROJECTION_LOSS";else if(inArtifact)lossBoundary="MODEL_ARTIFACT_TO_WORKER_CANDIDATE_LOSS";return {field,expected:value,inArtifact,inWorkerCandidates,inDeclarationCandidates,inWorkerResolution,inF6Audit,finalValue,inFinal,lossBoundary};});
  const counts=boundaries.reduce((a:any,x:any)=>(a[x.lossBoundary]=(a[x.lossBoundary]??0)+1,a),{});console.log(JSON.stringify({event:"product-e2e-1.6.8.6.row-matched-stage.diagnosed",id:tc.id,mode:tc.mode,workerOutcome:terminal.status,artifactSemantic,stageCounts:{workerCandidates:countCandidates(run?.candidates),declarationCandidates:countCandidates(run?.declarationCandidates),f6ResolutionRuns:audits.length},lossBoundaryCounts:counts,fields:boundaries,diagnosticNote:"goods-line ground truth is a representative subset; raw index boundaries are informational only and must not be interpreted as row-loss proof",guardrails:{measurementOnly:true,rowMatchingRequiredForGoodsLines:true,secondGroundTruthAwareModelCall:false,productionExtractionChanged:false,supplierSpecificRules:false,directNormalizedWrite:false}},null,2));
 }finally{if(runId){const job=await getIdpQueue().getJob(runId);if(job)try{await job.remove();}catch{}}await DeclarationFieldResolutionRunModel.deleteMany({declarationId});await LogicalDocumentModel.deleteMany({declarationId});if(runId)await ProcessingRunModel.deleteMany({_id:runId});if(uploadedId)await UploadedFileModel.deleteMany({_id:uploadedId});await DeclarationModel.deleteMany({_id:declarationId});}}
 }finally{await closeIdpQueue();await mongoose.disconnect();}}
main().catch(async e=>{console.error(e);try{await closeIdpQueue();}catch{}try{await mongoose.disconnect();}catch{}process.exitCode=1;});
