import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import mongoose from "mongoose";
import { env } from "../../src/config/env.js";
import { DocumentType } from "../../src/common/enums/documentType.js";
import { DeclarationModel } from "../../src/modules/declarations/declaration.model.js";
import { UploadedFileModel } from "../../src/modules/documents/document.model.js";
import { LogicalDocumentModel } from "../../src/modules/idp/domain/logicalDocument.model.js";
import { ProcessingRunModel } from "../../src/modules/idp/domain/processingRun.model.js";
import { DeclarationFieldResolutionRunModel } from "../../src/modules/idp/domain/declarationFieldResolution.model.js";
import { ProcessingStatus } from "../../src/modules/idp/domain/idp.types.js";
import { normalizeModelExtractionArtifacts } from "../../src/modules/idp/domain/modelExtractionArtifactPersistence.js";
import { enqueueDocumentProcessing } from "../../src/modules/idp/queue/idpProcessing.service.js";
import { closeIdpQueue, getIdpQueue } from "../../src/modules/idp/queue/idpQueue.js";
import { INVOICE_EXTRACTION_SKILL_VERSION } from "../../src/modules/idp/llm/invoiceExtractionSkill.js";
import { INVOICE_EXTRACTION_KNOWLEDGE_VERSION } from "../../src/modules/idp/llm/invoiceExtractionKnowledge.js";
import { PRODUCT_E2E_GENERALIZATION_CASES as CASES, PRODUCT_E2E_GENERALIZATION_CORPUS_ROOT as ROOT } from "./productE2EGeneralizationGroundTruth.js";

const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const norm=(v:unknown)=>String(v??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/İ/g,"I").toUpperCase().replace(/\s+/g," ").trim();
const num=(v:unknown)=>typeof v==="number"?v:Number(String(v??"").replace(/\s/g,"").replace(/,/g,"."));
const eqNum=(a:unknown,b:unknown)=>Number.isFinite(num(a))&&Number.isFinite(num(b))&&Math.abs(num(a)-num(b))<=Math.max(1e-6,Math.abs(num(b))*1e-6);
const canonCurrency=(v:unknown)=>({TL:"TRY",TRY:"TRY"} as Record<string,string>)[norm(v)]??norm(v);
const canonCountry=(v:unknown)=>({ABD:"US",USA:"US",US:"US"} as Record<string,string>)[norm(v).replace(/[^A-Z]/g,"")]??norm(v);
function finalScalar(nd:any,field:string){if(field==="invoiceNumber")return nd?.header?.invoiceNo;if(field==="currency")return nd?.header?.currency;if(field==="deliveryTerm")return nd?.trade?.deliveryTerm;if(field==="invoiceDate")return nd?.header?.invoiceDate;if(field==="grossWeight")return nd?.packageInfo?.grossKg;if(field==="netWeight")return nd?.packageInfo?.netKg;if(field==="originCountry")return nd?.trade?.origin;return undefined;}
function canonDate(v:unknown){if(v instanceof Date&&!Number.isNaN(v.getTime()))return v.toISOString().slice(0,10);const s=String(v??"").trim();const iso=s.match(/^(20\d{2}-\d{2}-\d{2})(?:T.*)?$/);return iso?iso[1]:s;}
function equivalent(field:string,a:unknown,e:unknown){if(a==null)return false;if(typeof e==="number")return eqNum(a,e);if(field==="currency")return canonCurrency(a)===canonCurrency(e);if(field==="originCountry")return canonCountry(a)===canonCountry(e);if(field==="invoiceDate")return canonDate(a)===canonDate(e);return norm(a)===norm(e);}
function semanticRows(artifacts:any[]){const rows:any[]=[];for(const artifact of [...artifacts].sort((a,b)=>(a.pageNumbers?.[0]??0)-(b.pageNumbers?.[0]??0))){const goods:Record<string,unknown[]>={};for(const f of artifact.parsedSemanticResponse.fields??[]){if(f.field.startsWith("goodsLines[].")&&Array.isArray(f.value))goods[f.field.slice(13)]=f.value;}const n=Math.max(0,...Object.values(goods).map(v=>v.length));for(let i=0;i<n;i++)rows.push(Object.fromEntries(Object.entries(goods).map(([k,v])=>[k,v[i]])));}return rows;}
function matchRow(e:any,rows:any[]){let best=-1,score=-1;for(let i=0;i<rows.length;i++){const a=rows[i]??{};let s=0;if(e.descriptionContains&&norm(a.description).includes(norm(e.descriptionContains)))s+=4;if(e.quantity!==undefined&&eqNum(a.quantity,e.quantity))s+=2;if(e.lineTotal!==undefined&&eqNum(a.lineTotal,e.lineTotal))s+=2;if(e.unitPrice!==undefined&&eqNum(a.unitPrice,e.unitPrice))s+=1;if(e.unit!==undefined&&norm(a.unit)===norm(e.unit))s+=1;if(s>score){score=s;best=i;}}return{index:best,score,row:best>=0?rows[best]:null};}
function rawCritical(raw:string){try{const x=JSON.parse(raw.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/, ""));return{xInvoiceDate:x?.invoiceDate??null,xCurrency:x?.currency??null,evidence:x?.criticalScalarEvidence??null};}catch{return{parseFailed:true};}}
async function waitTerminal(runId:string,id:string,timeout=120*60_000){const end=Date.now()+timeout;let last="";while(Date.now()<end){const run:any=await ProcessingRunModel.findById(runId).lean();assert(run,`${id}: run disappeared`);const job=await getIdpQueue().getJob(runId);assert(job,`${id}: job disappeared`);const state=await job.getState();const snap=`${run.status}/${run.currentStage}/${state}/attempt=${run.attempt}`;if(snap!==last){console.log(JSON.stringify({event:"product-e2e-1.6.8.18.progress",id,state:snap}));last=snap;}if(run.status===ProcessingStatus.FAILED||state==="failed")throw new Error(`${id}: worker failed: ${JSON.stringify(run.error)}`);if((run.status===ProcessingStatus.COMPLETED||run.status===ProcessingStatus.REVIEW_REQUIRED)&&state==="completed")return run;await sleep(500);}throw new Error(`${id}: timeout`);}

async function main(){
 assert.equal(env.llmEnabled,true,"1.6.8.18 requires LLM_ENABLED=true");assert.equal(env.llmVisionEnabled,true,"1.6.8.18 requires LLM_VISION_ENABLED=true");
 const requested=(process.env.GENERALIZATION_CASES??"mekar-ear-0068").split(",").map(x=>x.trim()).filter(Boolean);const selected=CASES.filter((x:any)=>requested.includes(x.id));assert.equal(selected.length,requested.length,`Unknown GENERALIZATION_CASES=${requested.join(",")}`);
 await mongoose.connect(env.mongoUri);try{for(const tc of selected as any[]){const pdfPath=path.join(ROOT,tc.pdf);const bytes=await fs.readFile(pdfPath);assert.equal(createHash("sha256").update(bytes).digest("hex"),tc.sourceSha256,`${tc.id}: frozen source changed`);const companyId=new mongoose.Types.ObjectId(),declarationId=new mongoose.Types.ObjectId();let uploadedId:any,runId="";try{
  await DeclarationModel.create({_id:declarationId,companyId,status:"DRAFT",normalizedData:{}});const stat=await fs.stat(pdfPath);const up:any=await UploadedFileModel.create({companyId,declarationId,type:DocumentType.INVOICE,fileName:tc.pdf,filePath:pdfPath,mimeType:"application/pdf",size:stat.size,extractionStatus:"PENDING",parseErrors:[]});uploadedId=up._id;const queued:any=await enqueueDocumentProcessing({companyId,declarationId:String(declarationId),uploadedFileId:String(uploadedId)});runId=String(queued._id);const terminal:any=await waitTerminal(runId,tc.id);
  const run:any=await ProcessingRunModel.findById(runId).lean();const declaration:any=await DeclarationModel.findById(declarationId).lean();const artifacts=normalizeModelExtractionArtifacts(run?.modelExtractionArtifacts);assert(artifacts.length>0,`${tc.id}: no first-class Qwen extraction artifact`);assert(artifacts.every(a=>a.skillVersion===INVOICE_EXTRACTION_SKILL_VERSION),`${tc.id}: stale extraction skill in persisted artifact`);
  const pages=artifacts.map(a=>({pageNumbers:a.pageNumbers,skillVersion:a.skillVersion,decision:a.parsedSemanticResponse.decision,acceptedCriticalScalars:a.parsedSemanticResponse.fields.filter(f=>["invoiceDate","currency"].includes(f.field)).map(f=>({field:f.field,value:f.value,evidence:f.evidence})),rawCriticalScalarResponse:rawCritical(a.rawModelResponse)}));
  const scalarFields=Object.entries(tc.expected??{}).filter(([k,v])=>k!=="goodsLines"&&v!==undefined).map(([field,expected])=>{const actual=finalScalar(declaration?.normalizedData??{},field);return{field,expected,actual:actual??null,status:actual==null?"MISSING":equivalent(field,actual,expected)?(String(actual)===String(expected)?"EXACT":"SEMANTIC_EQUIVALENT"):"WRONG"};});
  const artifactRows=semanticRows(artifacts),finalRows=Array.isArray(declaration?.normalizedData?.goodsLines)?declaration.normalizedData.goodsLines:[];const representativeGoods=(tc.expected?.goodsLines??[]).map((e:any,i:number)=>({expectedIndex:i,artifact:matchRow(e,artifactRows),final:matchRow(e,finalRows)}));
  const counts=scalarFields.reduce((a:any,x:any)=>(a[x.status]=(a[x.status]??0)+1,a),{});
  console.log(JSON.stringify({event:"product-e2e-1.6.8.18.real-qwen-grounded-corpus.measured",id:tc.id,workerOutcome:terminal.status,knowledgeVersion:INVOICE_EXTRACTION_KNOWLEDGE_VERSION,skillVersion:INVOICE_EXTRACTION_SKILL_VERSION,firstClassArtifactCount:artifacts.length,pages,scalarAccuracy:{counts,total:scalarFields.length,fields:scalarFields},goodsIntegrity:{artifactRowCount:artifactRows.length,finalRowCount:finalRows.length,representativeGoods},guardrails:{realProductionQwenCall:true,groundTruthUsedForMeasurementOnly:true,qwenPrimary:true,ocrPrimary:false,supplierSpecificRules:false,autonomousKnowledgeMutation:false,directNormalizedWrite:false}},null,2));
 }finally{if(runId){const job=await getIdpQueue().getJob(runId);if(job)try{await job.remove();}catch{}}await DeclarationFieldResolutionRunModel.deleteMany({declarationId});await LogicalDocumentModel.deleteMany({declarationId});if(runId)await ProcessingRunModel.deleteMany({_id:runId});if(uploadedId)await UploadedFileModel.deleteMany({_id:uploadedId});await DeclarationModel.deleteMany({_id:declarationId});}}
 }finally{await closeIdpQueue();await mongoose.disconnect();}}
main().catch(async e=>{console.error(e);try{await closeIdpQueue();}catch{}try{await mongoose.disconnect();}catch{}process.exitCode=1;});
